import imp
from tabela import Nrotores
from tabela import numeros
from tabela import Rescolhido
from tabela import Nescolhido
from tabela import rotor1
from tabela import rotor2
from tabela import rotor3
from tabela import rotor4
from tabela import rotor5
from tabela import rotores
from tabela import letras


def inversor(inv):
   match inv:
      case 'a':
         return 0
      case 'b':
         return 1 
      case 'c':
         return 2 
      case 'd':
         return 3 
      case 'e':
         return 4 
      case 'f':
         return 5 
      case 'g':
         return 6 
      case 'h':
         return 7 
      case 'i':
         return 8 
      case 'j':
         return 9 
      case 'k':
         return 10
      case 'l':
         return 11
      case 'm':
         return 12
      case 'n':
         return 13
      case 'o':
         return 14
      case 'p':
         return 15
      case 'q':
         return 16
      case 'r':
         return 17
      case 's':
         return 18
      case 't':
         return 19
      case 'u':
         return 20 
      case 'v':
         return 21 
      case 'w':
         return 22
      case 'x':
         return 23
      case 'y':
        return 24
      case 'z':
         return 25
      case _:
         return 'invalid'



def rot(num):
   match num:
      case '1':
         return rotor1
      case '2':
         return rotor2
      case '3':
         return rotor3
      case '4':
         return rotor4
      case '5':
         return rotor5
      
def rot1(L):
   match L:
      case 'a':
         return ((Rescolhido[0])[Nescolhido[0]][3])
      case 'b':
         return ((Rescolhido[0])[Nescolhido[0]][21])
      case 'c':
         return ((Rescolhido[0])[Nescolhido[0]][15]) 
      case 'd':
         return ((Rescolhido[0])[Nescolhido[0]][6])
      case 'e':
         return ((Rescolhido[0])[Nescolhido[0]][7])
      case 'f':
         return ((Rescolhido[0])[Nescolhido[0]][25])
      case 'g':
         return ((Rescolhido[0])[Nescolhido[0]][11]) 
      case 'h':
         return ((Rescolhido[0])[Nescolhido[0]][18]) 
      case 'i':
         return ((Rescolhido[0])[Nescolhido[0]][5])
      case 'j':
         return ((Rescolhido[0])[Nescolhido[0]][14]) 
      case 'k':
         return ((Rescolhido[0])[Nescolhido[0]][19])
      case 'l':
         return ((Rescolhido[0])[Nescolhido[0]][1])
      case 'm':
         return ((Rescolhido[0])[Nescolhido[0]][12])
      case 'n':
         return ((Rescolhido[0])[Nescolhido[0]][16])
      case 'o':
         return ((Rescolhido[0])[Nescolhido[0]][20])
      case 'p':
         return ((Rescolhido[0])[Nescolhido[0]][0])
      case 'q':
         return ((Rescolhido[0])[Nescolhido[0]][23])
      case 'r':
         return ((Rescolhido[0])[Nescolhido[0]][2])
      case 's':
         return ((Rescolhido[0])[Nescolhido[0]][8])
      case 't':
         return ((Rescolhido[0])[Nescolhido[0]][4])
      case 'u':
         return ((Rescolhido[0])[Nescolhido[0]][24]) 
      case 'v':
         return ((Rescolhido[0])[Nescolhido[0]][10])
      case 'w':
         return ((Rescolhido[0])[Nescolhido[0]][13])
      case 'x':
         return ((Rescolhido[0])[Nescolhido[0]][17])
      case 'y':
        return ((Rescolhido[0])[Nescolhido[0]][22])
      case 'z':
         return ((Rescolhido[0])[Nescolhido[0]][9])
      case '':
         return 'invalid'

def invrot1(L):
    match L:
        case 3:
            return 'a'
        case 21:
            return 'b'
        case 15:
            return 'c'
        case 6:
            return 'd'
        case 7:
            return 'e'
        case 25:
            return 'f'
        case 11:
            return 'g'
        case 18:
            return 'h'
        case 5:
            return 'i'
        case 14:
            return 'j'
        case 19:
            return 'k'
        case 1:
            return 'l'
        case 12:
            return 'm'
        case 16:
            return 'n'
        case 20:
            return 'o'
        case 0:
            return 'p'
        case 23:
            return 'q'
        case 2:
            return 'r'
        case 8:
            return 's'
        case 4:
            return 't'
        case 24:
            return 'u'
        case 10:
            return 'v'
        case 13:
            return 'w'
        case 17:
            return 'x'
        case 22:
            return 'y'
        case 9:
            return 'z'
        case '':
            return 'invalid'

def rot2(L):
   match L:
      case 'a':
         return ((Rescolhido[0])[Nescolhido[0]][19])
      case 'b':
         return ((Rescolhido[0])[Nescolhido[0]][1])
      case 'c':
         return ((Rescolhido[0])[Nescolhido[0]][2]) 
      case 'd':
         return ((Rescolhido[0])[Nescolhido[0]][23])
      case 'e':
         return ((Rescolhido[0])[Nescolhido[0]][12])
      case 'f':
         return ((Rescolhido[0])[Nescolhido[0]][9])
      case 'g':
         return ((Rescolhido[0])[Nescolhido[0]][21]) 
      case 'h':
         return ((Rescolhido[0])[Nescolhido[0]][6]) 
      case 'i':
         return ((Rescolhido[0])[Nescolhido[0]][24])
      case 'j':
         return ((Rescolhido[0])[Nescolhido[0]][16]) 
      case 'k':
         return ((Rescolhido[0])[Nescolhido[0]][20])
      case 'l':
         return ((Rescolhido[0])[Nescolhido[0]][0])
      case 'm':
         return ((Rescolhido[0])[Nescolhido[0]][11])
      case 'n':
         return ((Rescolhido[0])[Nescolhido[0]][14])
      case 'o':
         return ((Rescolhido[0])[Nescolhido[0]][4])
      case 'p':
         return ((Rescolhido[0])[Nescolhido[0]][5])
      case 'q':
         return ((Rescolhido[0])[Nescolhido[0]][22])
      case 'r':
         return ((Rescolhido[0])[Nescolhido[0]][15])
      case 's':
         return ((Rescolhido[0])[Nescolhido[0]][13])
      case 't':
         return ((Rescolhido[0])[Nescolhido[0]][7])
      case 'u':
         return ((Rescolhido[0])[Nescolhido[0]][8]) 
      case 'v':
         return ((Rescolhido[0])[Nescolhido[0]][18])
      case 'w':
         return ((Rescolhido[0])[Nescolhido[0]][17])
      case 'x':
         return ((Rescolhido[0])[Nescolhido[0]][25])
      case 'y':
        return ((Rescolhido[0])[Nescolhido[0]][3])
      case 'z':
         return ((Rescolhido[0])[Nescolhido[0]][10])
      case '':
         return 'invalid'

def invrot2(L):
    match L:
        case 19:
            return 'a'
        case 1:
            return 'b'
        case 2:
            return 'c'
        case 23:
            return 'd'
        case 12:
            return 'e'
        case 9:
            return 'f'
        case 21:
            return 'g'
        case 6:
            return 'h'
        case 24:
            return 'i'
        case 16:
            return 'j'
        case 20:
            return 'k'
        case 0:
            return 'l'
        case 11:
            return 'm'
        case 14:
            return 'n'
        case 4:
            return 'o'
        case 5:
            return 'p'
        case 22:
            return 'q'
        case 15:
            return 'r'
        case 13:
            return 's'
        case 7:
            return 't'
        case 8:
            return 'u'
        case 18:
            return 'v'
        case 17:
            return 'w'
        case 25:
            return 'x'
        case 3:
            return 'y'
        case 10:
            return 'z'
        case '':
            return 'invalid'

def rot3(L):
   match L:
      case 'a':
         return ((Rescolhido[0])[Nescolhido[0]][7])
      case 'b':
         return ((Rescolhido[0])[Nescolhido[0]][1])
      case 'c':
         return ((Rescolhido[0])[Nescolhido[0]][9]) 
      case 'd':
         return ((Rescolhido[0])[Nescolhido[0]][25])
      case 'e':
         return ((Rescolhido[0])[Nescolhido[0]][5])
      case 'f':
         return ((Rescolhido[0])[Nescolhido[0]][0])
      case 'g':
         return ((Rescolhido[0])[Nescolhido[0]][23]) 
      case 'h':
         return ((Rescolhido[0])[Nescolhido[0]][21]) 
      case 'i':
         return ((Rescolhido[0])[Nescolhido[0]][3])
      case 'j':
         return ((Rescolhido[0])[Nescolhido[0]][10]) 
      case 'k':
         return ((Rescolhido[0])[Nescolhido[0]][18])
      case 'l':
         return ((Rescolhido[0])[Nescolhido[0]][11])
      case 'm':
         return ((Rescolhido[0])[Nescolhido[0]][22])
      case 'n':
         return ((Rescolhido[0])[Nescolhido[0]][24])
      case 'o':
         return ((Rescolhido[0])[Nescolhido[0]][13])
      case 'p':
         return ((Rescolhido[0])[Nescolhido[0]][12])
      case 'q':
         return ((Rescolhido[0])[Nescolhido[0]][4])
      case 'r':
         return ((Rescolhido[0])[Nescolhido[0]][8])
      case 's':
         return ((Rescolhido[0])[Nescolhido[0]][6])
      case 't':
         return ((Rescolhido[0])[Nescolhido[0]][17])
      case 'u':
         return ((Rescolhido[0])[Nescolhido[0]][20]) 
      case 'v':
         return ((Rescolhido[0])[Nescolhido[0]][19])
      case 'w':
         return ((Rescolhido[0])[Nescolhido[0]][15])
      case 'x':
         return ((Rescolhido[0])[Nescolhido[0]][16])
      case 'y':
        return ((Rescolhido[0])[Nescolhido[0]][14])
      case 'z':
         return ((Rescolhido[0])[Nescolhido[0]][2])
      case '':
         return 'invalid'

def invrot3(L):
    match L:
        case 7:
            return 'a'
        case 1:
            return 'b'
        case 9:
            return 'c'
        case 25:
            return 'd'
        case 5:
            return 'e'
        case 0:
            return 'f'
        case 23:
            return 'g'
        case 21:
            return 'h'
        case 3:
            return 'i'
        case 10:
            return 'j'
        case 18:
            return 'k'
        case 11:
            return 'l'
        case 22:
            return 'm'
        case 24:
            return 'n'
        case 13:
            return 'o'
        case 12:
            return 'p'
        case 4:
            return 'q'
        case 8:
            return 'r'
        case 6:
            return 's'
        case 17:
            return 't'
        case 20:
            return 'u'
        case 19:
            return 'v'
        case 15:
            return 'w'
        case 16:
            return 'x'
        case 14:
            return 'y'
        case 2:
            return 'z'
        case '':
            return 'invalid'

def rot4(L):
   match L:
      case 'a':
         return ((Rescolhido[0])[Nescolhido[0]][23])
      case 'b':
         return ((Rescolhido[0])[Nescolhido[0]][24])
      case 'c':
         return ((Rescolhido[0])[Nescolhido[0]][6]) 
      case 'd':
         return ((Rescolhido[0])[Nescolhido[0]][13])
      case 'e':
         return ((Rescolhido[0])[Nescolhido[0]][7])
      case 'f':
         return ((Rescolhido[0])[Nescolhido[0]][5])
      case 'g':
         return ((Rescolhido[0])[Nescolhido[0]][11]) 
      case 'h':
         return ((Rescolhido[0])[Nescolhido[0]][20]) 
      case 'i':
         return ((Rescolhido[0])[Nescolhido[0]][1])
      case 'j':
         return ((Rescolhido[0])[Nescolhido[0]][19]) 
      case 'k':
         return ((Rescolhido[0])[Nescolhido[0]][15])
      case 'l':
         return ((Rescolhido[0])[Nescolhido[0]][25])
      case 'm':
         return ((Rescolhido[0])[Nescolhido[0]][8])
      case 'n':
         return ((Rescolhido[0])[Nescolhido[0]][4])
      case 'o':
         return ((Rescolhido[0])[Nescolhido[0]][17])
      case 'p':
         return ((Rescolhido[0])[Nescolhido[0]][3])
      case 'q':
         return ((Rescolhido[0])[Nescolhido[0]][21])
      case 'r':
         return ((Rescolhido[0])[Nescolhido[0]][14])
      case 's':
         return ((Rescolhido[0])[Nescolhido[0]][2])
      case 't':
         return ((Rescolhido[0])[Nescolhido[0]][22])
      case 'u':
         return ((Rescolhido[0])[Nescolhido[0]][12]) 
      case 'v':
         return ((Rescolhido[0])[Nescolhido[0]][0])
      case 'w':
         return ((Rescolhido[0])[Nescolhido[0]][10])
      case 'x':
         return ((Rescolhido[0])[Nescolhido[0]][18])
      case 'y':
        return ((Rescolhido[0])[Nescolhido[0]][9])
      case 'z':
         return ((Rescolhido[0])[Nescolhido[0]][6])
      case '':
         return 'invalid'

def invrot4(L):
    match L:
        case 23:
            return 'a'
        case 24:
            return 'b'
        case 6:
            return 'c'
        case 13:
            return 'd'
        case 7:
            return 'e'
        case 5:
            return 'f'
        case 11:
            return 'g'
        case 20:
            return 'h'
        case 1:
            return 'i'
        case 19:
            return 'j'
        case 15:
            return 'k'
        case 25:
            return 'l'
        case 8:
            return 'm'
        case 4:
            return 'n'
        case 17:
            return 'o'
        case 3:
            return 'p'
        case 21:
            return 'q'
        case 14:
            return 'r'
        case 2:
            return 's'
        case 22:
            return 't'
        case 12:
            return 'u'
        case 0:
            return 'v'
        case 10:
            return 'w'
        case 18:
            return 'x'
        case 9:
            return 'y'
        case 6:
            return 'z'
        case '':
            return 'invalid'

def rot5(L):
   match L:
      case 'a':
         return ((Rescolhido[0])[Nescolhido[0]][6])
      case 'b':
         return ((Rescolhido[0])[Nescolhido[0]][21])
      case 'c':
         return ((Rescolhido[0])[Nescolhido[0]][25]) 
      case 'd':
         return ((Rescolhido[0])[Nescolhido[0]][20])
      case 'e':
         return ((Rescolhido[0])[Nescolhido[0]][15])
      case 'f':
         return ((Rescolhido[0])[Nescolhido[0]][19])
      case 'g':
         return ((Rescolhido[0])[Nescolhido[0]][10]) 
      case 'h':
         return ((Rescolhido[0])[Nescolhido[0]][17]) 
      case 'i':
         return ((Rescolhido[0])[Nescolhido[0]][9])
      case 'j':
         return ((Rescolhido[0])[Nescolhido[0]][22]) 
      case 'k':
         return ((Rescolhido[0])[Nescolhido[0]][14])
      case 'l':
         return ((Rescolhido[0])[Nescolhido[0]][3])
      case 'm':
         return ((Rescolhido[0])[Nescolhido[0]][5])
      case 'n':
         return ((Rescolhido[0])[Nescolhido[0]][11])
      case 'o':
         return ((Rescolhido[0])[Nescolhido[0]][4])
      case 'p':
         return ((Rescolhido[0])[Nescolhido[0]][1])
      case 'q':
         return ((Rescolhido[0])[Nescolhido[0]][18])
      case 'r':
         return ((Rescolhido[0])[Nescolhido[0]][24])
      case 's':
         return ((Rescolhido[0])[Nescolhido[0]][0])
      case 't':
         return ((Rescolhido[0])[Nescolhido[0]][23])
      case 'u':
         return ((Rescolhido[0])[Nescolhido[0]][16]) 
      case 'v':
         return ((Rescolhido[0])[Nescolhido[0]][12])
      case 'w':
         return ((Rescolhido[0])[Nescolhido[0]][7])
      case 'x':
         return ((Rescolhido[0])[Nescolhido[0]][2])
      case 'y':
        return ((Rescolhido[0])[Nescolhido[0]][13])
      case 'z':
         return ((Rescolhido[0])[Nescolhido[0]][8])
      case '':
         return 'invalid'

def invrot5(L):
    match L:
        case 6:
            return 'a'
        case 21:
            return 'b'
        case 25:
            return 'c'
        case 20:
            return 'd'
        case 15:
            return 'e'
        case 19:
            return 'f'
        case 10:
            return 'g'
        case 17:
            return 'h'
        case 9:
            return 'i'
        case 22:
            return 'j'
        case 14:
            return 'k'
        case 3:
            return 'l'
        case 5:
            return 'm'
        case 11:
            return 'n'
        case 4:
            return 'o'
        case 1:
            return 'p'
        case 18:
            return 'q'
        case 24:
            return 'r'
        case 0:
            return 's'
        case 23:
            return 't'
        case 16:
            return 'u'
        case 12:
            return 'v'
        case 7:
            return 'w'
        case 2:
            return 'x'
        case 13:
            return 'y'
        case 8:
            return 'z'
        case '':
            return 'invalid'
         
def espelho (L):
   match L:
      case 'a':
         return 'i'
      case 'b':
         return 'x'
      case 'c':
         return 'u'
      case 'd':
         return 'h'
      case 'e':
         return 'f'
      case 'f':
         return 'e'
      case 'g':
         return 'z'
      case 'h':
         return 'd'
      case 'i':
         return 'a'
      case 'j':
         return 'o'
      case 'k':
         return 'm'
      case 'l':
         return 't'
      case 'm':
         return 'l'
      case 'n':
         return 'q'
      case 'o':
         return 'j'
      case 'p':
         return 'w'
      case 'q':
         return 'n'
      case 'r':
         return 's'
      case 's':
         return 'r'
      case 't':
         return 'l'
      case 'u':
         return 'c'
      case 'v':
         return 'y'
      case 'w':
         return 'p'
      case 'x':
         return 'b'
      case 'y':
         return 'v'
      case 'z':
         return 'g'
      case '':
         return 'invalid'

def convert(self, codigo):
	lista = []
	lista [:0] = codigo
   
codigo = input("digite o código")
print (convert(codigo))

