rotor1 = ['xyzwhibgdpfqjkeautnlcomrsv',
'yzwhibgdpfqjkeautnlcomrsvx',
'zwhibgdpfqjkeautnlcomrsvxy',
'whibgdpfqjkeautnlcomrsvxyz',
'hibgdpfqjkeautnlcomrsvxyzw',
'ibgdpfqjkeautnlcomrsvxyzwh',
'bgdpfqjkeautnlcomrsvxyzwhi',
'gdpfqjkeautnlcomrsvxyzwhib',
'dpfqjkeautnlcomrsvxyzwhibg',
'pfqjkeautnlcomrsvxyzwhibgd',
'fqjkeautnlcomrsvxyzwhibgdp',
'qjkeautnlcomrsvxyzwhibgdpf',
'jkeautnlcomrsvxyzwhibgdpfq',
'keautnlcomrsvxyzwhibgdpfqj',
'eautnlcomrsvxyzwhibgdpfqjk',
'autnlcomrsvxyzwhibgdpfqjke',
'utnlcomrsvxyzwhibgdpfqjkea',
'tnlcomrsvxyzwhibgdpfqjkeau',
'nlcomrsvxyzwhibgdpfqjkeaut',
'lcomrsvxyzwhibgdpfqjkeautn',
'comrsvxyzwhibgdpfqjkeautnl',
'omrsvxyzwhibgdpfqjkeautnlc',
'mrsvxyzwhibgdpfqjkeautnlco',
'rsvxyzwhibgdpfqjkeautnlcom',
'svxyzwhibgdpfqjkeautnlcomr',
'vxyzwhibgdpfqjkeautnlcomrs',]

rotor2 = ['pjoxzcaqwtklhmvnfigsdbreyu',
'joxzcaqwtklhmvnfigsdbreyup',
'oxzcaqwtklhmvnfigsdbreyupj',
'xzcaqwtklhmvnfigsdbreyupjo',
'zcaqwtklhmvnfigsdbreyupjox',
'caqwtklhmvnfigsdbreyupjoxz',
'aqwtklhmvnfigsdbreyupjoxzc',
'qwtklhmvnfigsdbreyupjoxzca',
'wtklhmvnfigsdbreyupjoxzcaq',
'tklhmvnfigsdbreyupjoxzcaqw',
'klhmvnfigsdbreyupjoxzcaqwt',
'lhmvnfigsdbreyupjoxzcaqwtk',
'hmvnfigsdbreyupjoxzcaqwtkl',
'mvnfigsdbreyupjoxzcaqwtklh',
'vnfigsdbreyupjoxzcaqwtklhm',
'nfigsdbreyupjoxzcaqwtklhmv',
'figsdbreyupjoxzcaqwtklhmvn',
'igsdbreyupjoxzcaqwtklhmvnf',
'gsdbreyupjoxzcaqwtklhmvnfi',
'sdbreyupjoxzcaqwtklhmvnfig',
'dbreyupjoxzcaqwtklhmvnfigs',
'breyupjoxzcaqwtklhmvnfigsd',
'reyupjoxzcaqwtklhmvnfigsdb',
'eyupjoxzcaqwtklhmvnfigsdbr',
'yupjoxzcaqwtklhmvnfigsdbre',
'upjoxzcaqwtklhmvnfigsdbrey']

rotor3 = ['pyqxmrsvteiozklawnhgjbcufd',
'yqxmrsvteiozklawnhgjbcufdp',
'qxmrsvteiozklawnhgjbcufdpy',
'xmrsvteiozklawnhgjbcufdpyq',
'mrsvteiozklawnhgjbcufdpyqx',
'rsvteiozklawnhgjbcufdpyqxm',
'svteiozklawnhgjbcufdpyqxmr',
'vteiozklawnhgjbcufdpyqxmrs',
'teiozklawnhgjbcufdpyqxmrsv',
'eiozklawnhgjbcufdpyqxmrsvt',
'iozklawnhgjbcufdpyqxmrsvte',
'ozklawnhgjbcufdpyqxmrsvtei',
'zklawnhgjbcufdpyqxmrsvteio',
'klawnhgjbcufdpyqxmrsvteioz',
'lawnhgjbcufdpyqxmrsvteiozk',
'awnhgjbcufdpyqxmrsvteiozkl',
'wnhgjbcufdpyqxmrsvteiozkla',
'nhgjbcufdpyqxmrsvteiozklaw',
'hgjbcufdpyqxmrsvteiozklawn',
'gjbcufdpyqxmrsvteiozklawnh',
'jbcufdpyqxmrsvteiozklawnhg',
'bcufdpyqxmrsvteiozklawnhgj',
'cufdpyqxmrsvteiozklawnhgjb',
'ufdpyqxmrsvteiozklawnhgjbc',
'fdpyqxmrsvteiozklawnhgjbcu',
'dpyqxmrsvteiozklawnhgjbcuf']

rotor4 = ['tkyubaeohsmvdqzxwpfrcngjli',
'kyubaeohsmvdqzxwpfrcngjlit',
'yubaeohsmvdqzxwpfrcngjlitk',
'ubaeohsmvdqzxwpfrcngjlitky',
'baeohsmvdqzxwpfrcngjlitkyu',
'aeohsmvdqzxwpfrcngjlitkyub',
'eohsmvdqzxwpfrcngjlitkyuba',
'ohsmvdqzxwpfrcngjlitkyubae',
'hsmvdqzxwpfrcngjlitkyubaeo',
'smvdqzxwpfrcngjlitkyubaeoh',
'mvdqzxwpfrcngjlitkyubaeohs',
'vdqzxwpfrcngjlitkyubaeohsm',
'dqzxwpfrcngjlitkyubaeohsmv',
'qzxwpfrcngjlitkyubaeohsmvd',
'zxwpfrcngjlitkyubaeohsmvdq',
'xwpfrcngjlitkyubaeohsmvdqz',
'wpfrcngjlitkyubaeohsmvdqzx',
'pfrcngjlitkyubaeohsmvdqzxw',
'frcngjlitkyubaeohsmvdqzxwp',
'rcngjlitkyubaeohsmvdqzxwpf',
'cngjlitkyubaeohsmvdqzxwpfr',
'ngjlitkyubaeohsmvdqzxwpfrc',
'gjlitkyubaeohsmvdqzxwpfrcn',
'jlitkyubaeohsmvdqzxwpfrcng',
'litkyubaeohsmvdqzxwpfrcngj',
'itkyubaeohsmvdqzxwpfrcngjl']

rotor5 = ['yipenwoftqrlzjabmcxvkhgsud',
'ipenwoftqrlzjabmcxvkhgsudy',
'penwoftqrlzjabmcxvkhgsudyi',
'enwoftqrlzjabmcxvkhgsudyip',
'nwoftqrlzjabmcxvkhgsudyipe',
'woftqrlzjabmcxvkhgsudyipen',
'oftqrlzjabmcxvkhgsudyipenw',
'ftqrlzjabmcxvkhgsudyipenwo',
'tqrlzjabmcxvkhgsudyipenwof',
'qrlzjabmcxvkhgsudyipenwoft',
'rlzjabmcxvkhgsudyipenwoftq',
'lzjabmcxvkhgsudyipenwoftqr',
'zjabmcxvkhgsudyipenwoftqrl',
'jabmcxvkhgsudyipenwoftqrlz',
'abmcxvkhgsudyipenwoftqrlzj',
'bmcxvkhgsudyipenwoftqrlzja',
'mcxvkhgsudyipenwoftqrlzjab',
'cxvkhgsudyipenwoftqrlzjabm',
'xvkhgsudyipenwoftqrlzjabmc',
'vkhgsudyipenwoftqrlzjabmcx',
'khgsudyipenwoftqrlzjabmcxv',
'hgsudyipenwoftqrlzjabmcxvk',
'gsudyipenwoftqrlzjabmcxvkh',
'sudyipenwoftqrlzjabmcxvkhg',
'udyipenwoftqrlzjabmcxvkhgs',
'dyipenwoftqrlzjabmcxvkhgsu']

espelho = ["lushqoxdmznaikfrepcybwvgt"]

rotores = []
letras = []

funrot = []

numeros = []
Nrotores = []

Rescolhido = []
Nescolhido = []

msg = []

